### PR TITLE
Added missing WISEREP spectra

### PR DESCRIPTION
**Pull request by jparrent**
I have now added the missing files to the appropriate sub-directories. Some of the entries, however, are not present because I discovered they refer to one of the following:
*rapid reduction spectra; i.e. we already have the final reduction and would not like to duplicate.
*non-SN spectrum, e.g., host spectrum or hi-res Na D spectrum.

For the last year (this year, 2016), I have updated the html page and spectra out to Apr 1st.

That said, feel free to let me know of the stuff that's still missing; at least for the list you gave me earlier, I'm keeping track of which ones we don't want.

### CODE REVIEW

**Comment by guillochon** [comment]
This is now live on the website, we still have some missing events but now mostly from 2016 (which I think is expected), and far fewer. Still a couple of older SN that have missing spectra for some reason that should be on WISeREP but we're almost complete now.

Here's the new missing list (now just 112 missing):

```
K0905-3
SN2006be
SN2006ca
SN2006cu
SN2007gj
SN2007rw
SN2008dh
SN2009ds
SN2009ev
SN2009iw
SN2009nr
SNF20080612-003
iPTF14bdn
PS1-10afx
SN2010A
SN2010ev
Gaia16add
Gaia16aea
Gaia16aec
Gaia16afe
Gaia16afj
Gaia16afo
Gaia16afq
Gaia16afw
OGLE16alt
SN2015bi
SN2015bj
SN2015bk
SN2015bl
SN2016A
SN2016aai
SN2016aak
SN2016ac
SN2016acx
SN2016adg
SN2016adi
SN2016adj
SN2016adk
SN2016adl
SN2016adn
SN2016adp
SN2016adq
SN2016aew
SN2016aex
SN2016aey
SN2016aez
SN2016afa
SN2016afj
SN2016afk
SN2016ag
SN2016ah
SN2016ahb
SN2016aix
SN2016aiy
SN2016aj
SN2016ajb
SN2016aje
SN2016ajm
SN2016ajw
SN2016ak
SN2016al
SN2016am
SN2016apz
SN2016aqa
SN2016aqb
SN2016B
SN2016C
SN2016D
SN2016E
SN2016ek
SN2016el
SN2016em
SN2016en
SN2016eo
SN2016ep
SN2016eq
SN2016er
SN2016es
SN2016F
SN2016G
SN2016H
SN2016I
SN2016J
SN2016K
SN2016M
SN2016P
SN2016sl
SN2016W
SN2016ww
SN2016X
SN2016xb
SN2016Z
SN2016zb
SN2016zc
SN2016zd
SN2016ze
SN2016zr
CSS130214-110748+243938
CSS141015-212902+051800
CSS160208-135632+203038
Eta Carinae
PTF09ilp
SDSS-SN-041
SDSS-SN-051
SDSS-SN-060
SDSS-SN-064
SDSS-SN-065
SDSS-SN-076
SDSS-SN-084
SDSS-SN-095
SDSS-SN-119
SN2016za
```

Let me know if you think any of these shouldn't be missing, otherwise I'll merge.

**Comment by jparrent** [comment]
I'm guessing most are for "rapid reductions", whereas we should already
have most of the final reductions. I will quality control this list later,
but approved for merge.

**Comment by guillochon** [comment]
The events on this list have no spectra at all from any source, but are listed on WISeREP and thus likely have a spectrum from them (although it might be a rapid reduction).

Anyway, I'll go ahead and merge and we can try and nab the remainder later. We should have a general "hitlist" of typed supernovae with no spectra (not just WISeREP), this is the data we'd like to collect eventually.

**Comment by jparrent** [comment]
Agreed, I'll check out that list tomorrow.

**Pull request merged**
